/* SQL FILE TO CREATE DATABASE TABLE TO REGISTER AND LOGIN USERS */

CREATE TABLE IF DOESNT EXISTS  users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT,
  password TEXT,
  email TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);